# Files
executable = scriptcondor.sh
#output = outputcondorZToMuMu/log/scriptcondor_$(Process).out
#error = outputcondorZToMuMu/log/scriptcondor_$(Process).err
#log = outputcondorZToMuMu/log/scriptcondor_$(Process).log
output = outputcondorZToMuMu_MC/log/scriptcondor_$(Process).out
error = outputcondorZToMuMu_MC/log/scriptcondor_$(Process).err
log = outputcondorZToMuMu_MC/log/scriptcondor_$(Process).log
#arguments    = $(Process)


transfer_input_files = $(filename)
arguments            = $(filename)  outputcondorZToMuMu_MC/output_$(Process).root ZToMuMu



# File transfer behavior
#should_transfer_files = no
#when_to_transfer_output = ON_EXIT

# Resource requests
#request_cpus   = 4
request_memory = 100MB
request_disk   = 100MB

# Optional resource requests
#+xcount = 4            # Request 4 cores
#+maxMemory = 4000      # Request 4GB of RAM
#+maxWallTime = 120     # Request 2 hrs of wall clock time
#+remote_queue = "osg"  # Request the OSG queue

# Run job
#queue filename matching files /pnfs/iihe/cms/store/user/lathomas/Muon/Run2022C_PromptReco_v1_DataRun3_L1Study_SingleMuforJME/220822_150627/0000/output_*.root /pnfs/iihe/cms/store/user/lathomas/SingleMuon/Run2022C_PromptReco_v1_DataRun3_L1Study_SingleMuforJME/220817_075727/0000/output_*.root

# default files:
#queue filename matching files /pnfs/iihe/cms/store/user/lathomas/*Muon*/*_PromptReco_v*_DataRun3_L1Study_ZToMuMu/220909*/*/*.root

# Monte Carlo events:
queue filename matching files /pnfs/iihe/cms/store/user/lathomas/DYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8/Run3Winter22MiniAOD_122X_mcRun3_2021_realistic_v9_ext1_v1_DataRun3_L1Study_ZToMuMu/220913_202809/0000/*.root

#queue filename matching files /pnfs/iihe/cms/store/user/lathomas/SingleMuon/Run2022B_PromptReco_v1_DataRun3_L1Study_SingleMuforJME/220908_123342/0000/*.root
#queue 100 
